package util

import (
	"errors"
	"io"
	"io/fs"
)

func ReadFile(fsys fs.FS, name string) ([]byte, error) {
	f, err := fsys.Open(name)
	if err != nil {
		return nil, err
	}
	defer f.Close()

	return io.ReadAll(f)
}

// Generated by Gemini
// DirectoryExists checks if a directory exists in the given filesystem.
func DirectoryExists(fsys fs.FS, name string) (bool, error) {
	// 1. Use fs.Stat to get info on the path
	info, err := fs.Stat(fsys, name)
	if err != nil {
		// 2. If the error is fs.ErrNotExist, it doesn't exist.
		//    Return false and no error.
		if errors.Is(err, fs.ErrNotExist) {
			return false, nil
		}
		// 3. For any other error, return it.
		return false, err
	}

	// 4. If there was no error, check if the path is a directory.
	return info.IsDir(), nil
}
