name: Archive build artifacts

on: [push]

jobs:
  build:
    strategy:
      matrix:
        os: [ 'windows-latest', 'macos-latest']
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19.x

      - name: Build
        run: cd cmd/gosu && go build -v .

      - name: Archive build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.os }}-build
          path: cmd/gosu

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: cmd/gosu
          token: ${{ secrets.CUSTOM_GITHUB_TOKEN }}
        env:
          GITHUB_REPOSITORY: hndada/gosu
